---
title: "Project-1-source-code"
output: html_document
date: "2024-04-02"
---
## Preparing task
Use the library
```{r}
# All packages used in this script:
library(tidyverse)
library(here)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(readr)
library(showtext)
#install.packages("janitor")
library(janitor)
library(glue)
library(ggtext)
#install.packages("mapdata")
library(mapdata)
#install.packages("biscale")
library(biscale)
#install.packages("gridExtra")
library(gridExtra)
#install.packages("patchwork")
library(patchwork)
```

Load the data 
```{r}
tornados <- read_csv("data/tornados.csv")
```

Preprocess data
```{r}
# Filter out Alaska and Hawaii. These two states do not follow the common path with other states in the US.
tornados <- tornados |>
  filter(
    !st %in% c("HI", "AK"),
    slat > 25
  )
```

** Common Utils **

Create a theme
```{r}
font_add_google("DM Sans", "DM Sans")
showtext_auto()
main_font = "DM Sans"

theme_1b <- function() {
  theme_minimal(
    base_family = main_font,
    base_size = 11,
    base_line_size = 11/22,
    base_rect_size = 11/22
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.grid.major.y = element_line(color = "grey80"),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_line(color = "grey80"),
    panel.grid.minor.x = element_blank(),
    axis.title.x = element_text(size = 12, hjust = 0.5, face = "bold"),
    axis.title.y = element_text(size = 12, hjust = 0.5, face = "bold"),
    legend.title = element_text(face = "bold")
  )
}
```

```{r}
theme_1d <- function() {
    theme_minimal(
    base_family = main_font,
    base_size = 11,
    base_line_size = 11/22,
    base_rect_size = 11/22
  ) + 
  theme(
    plot.title = element_text(size = 12, hjust = 0.5, face = "bold"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.title.x = element_text(size = 8, hjust = 0.5, face = "bold"),
    axis.title.y = element_text(size = 8, hjust = 0.5, face = "bold"),
    axis.text.x = element_text(size = 5),
    axis.text.y = element_text(size = 5)
  )
}
```

Color palette
```{r}
pal <- c('#00202e', '#003f5c', '#2c4875', '#8a508f', '#bc5090', '#ff6361', '#ff8531', '#ffa600', '#ffd380','#35A29F')

pal_4 <- c("#1d4877", "#1b8a5a", "#fbb021", "#f68838", "#ee3e32")
pal_4 <- c(NA, colorRampPalette(pal_4)(13))
```

## Question 1

# Mini Question 1
```{r}
bg <- "white"

# Create a US map
df_state <- map_data("state")

# Create a df to use for plotting different months
df_base <- tornados %>%
  mutate(
    month = format(date, "%b"),
    month = factor(month, levels = c("Jan", "Apr", "Jul", "Oct", "Feb", "May", "Aug", "Nov", "Mar", "Jun", "Sep", "Dec")),
  )

# Create a dataframe for text position
df_base_labs <- df_base |>
  distinct(month) |>
  mutate(
    x = mean(range(df_state$long)),
    y = max(df_state$lat) + 2
  )

distribution_map <- ggplot(data = df_state) +
  geom_polygon(aes(long, lat, group = group), colour = "black", fill = NA, linewidth = 0.1) +
  geom_density2d_filled(data = df_base, aes(slon, slat), alpha = 0.6, contour_var = "count") +
  geom_text(aes(x, y, label = month), df_base_labs, family = main_font, size = 4, colour = "black") +
  scale_fill_manual(values = pal_4, na.value = NA) +
  facet_wrap(~month, nrow = 3) +
  coord_map(clip = "off") +
  theme_void() +
  labs(title = "US Tornado Patterns by Month") +
  theme(
    text = element_text(family = main_font, size = 48, lineheight = 0.3, colour = "black"),
    plot.background = element_rect(fill = bg, colour = bg),
    plot.caption = element_markdown(colour = "black", hjust = 0.5, margin = margin(t = 20)),
    plot.margin = margin(b = 20, t = 50, r = 50, l = 50),
    legend.position = "none",
    strip.text = element_blank(),
    plot.title = element_text(face = "bold", size = 15, hjust = 0.5, margin = margin(b = 20, unit = "pt"))
  )

distribution_map
```

# Mini Question 2
```{r}
data_1b <- data.frame(tornados)

data_1b$mag <- as.numeric(as.character(data_1b$mag))

yearly_count <- data_1b %>%
  group_by(yr) %>%
  summarise(TotalTornadoes = n())

# Define a function to calculate mode
get_mode <- function(v) {
  uniqv <- unique(na.omit(v))
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

# Summarizing the data by year
yearly_summary <- data_1b %>%
  group_by(yr) %>%
  summarise(
    AverageMag = mean(mag, na.rm = TRUE),
    AverageWidth = median(wid, na.rm = TRUE),
    AverageLength = median(len, na.rm = TRUE)
  )

special_year <- c(1974, 2011, 2020)

plot_occurrences <- ggplot(yearly_count, aes(x = yr, y = TotalTornadoes)) +
  geom_line(size = 1, color = pal[2]) +
  geom_vline(xintercept = special_year, linetype = 2) +
  annotate("text", x = 2011, y = 470, size = 1.5, label = "2011 Super Outbreak", angle = 90, vjust = -0.5) +
  annotate("text", x = 1974, y = 475, size = 1.5, label = "1974 Super Outbreak", angle = 90, vjust = -0.5) +
  annotate("text", x = 2020, y = 620, size = 1.5, label = "2020 Easter Tornado Outbreak", angle = 90, vjust = -0.5) +
  labs(title = "Total Yearly Tornado Occurrences",
       x = "Year",
       y = "Number of Tornadoes") +
  theme_1d()

# Creating three separate plots
plot_mag <- ggplot(yearly_summary, aes(x = yr, y = AverageMag)) +
  geom_line(size = 1, color = pal[4]) +
  geom_vline(xintercept = special_year, linetype = 2) +
  labs(title = "Annual Average Tornado Magnitude",
       x = "Year",
       y = "Average Magnitude") +
  theme_1d()

plot_width <- ggplot(yearly_summary, aes(x = yr, y = AverageWidth)) +
  geom_line(size = 1, color = pal[6]) +
    geom_vline(xintercept = special_year, linetype = 2) +
  labs(title = "Annual Median Tornado Width",
       x = "Year",
       y = "Average Width (yards)") +
  theme_1d()

plot_length <- ggplot(yearly_summary, aes(x = yr, y = AverageLength)) +
  geom_line(size = 0.8, color = pal[8]) +
  geom_vline(xintercept = special_year, linetype = 2) +
  labs(title = "Annual Median Tornado Length",
       x = "Year",
       y = "Average Length (miles)") +
  theme_1d()

plot_occurrences <- plot_occurrences + theme(plot.margin = margin(1, 3, 3, 1, "mm"))
plot_mag <- plot_mag + theme(plot.margin = margin(1, 1, 3, 3, "mm"))
plot_width <- plot_width + theme(plot.margin = margin(3, 3, 1, 1, "mm"))
plot_length <- plot_length + theme(plot.margin = margin(3, 1, 1, 3, "mm"))

combined_plot <- grid.arrange(
  plot_occurrences, plot_mag, plot_width, plot_length, 
  ncol = 2
)
```

## Question 2

# Mini Question 1

```{r}
# Select the used data for plot 2.1
combined_data <- tornados %>%
  select(st, om, fat, inj) %>%
  group_by(st) %>%
  summarise(number_of_tornados = n(),
            number_of_injuries = sum(inj, na.rm = TRUE),
            number_of_fatalities = sum(fat, na.rm = TRUE),
            fatality_rate = number_of_fatalities / number_of_tornados) %>%
  filter(fatality_rate > 0.1, st != "AL") |>
  arrange(desc(fatality_rate)) 

# Add the column to inform the number of tornados range 
combined_data <- combined_data %>%
  mutate(tornado_color_factor = case_when(
    number_of_tornados < 1000  ~ "0-999",
    number_of_tornados >= 1000 & number_of_tornados < 2000 ~ "1000-1999",
    number_of_tornados >= 2000 & number_of_tornados < 3000 ~ "2000-2999",
    number_of_tornados >= 3000 & number_of_tornados < 4000 ~ "3000-3999",
    TRUE ~ "4000+"
  ))

# Choose the color for the tornado range
colors <- c("0-999" = pal[10], "1000-1999" = pal[9], "2000-2999" = pal[7], "3000-3999" = pal[2], "4000+" = pal[6])

# Create the bubble chart
bubble_chart <- ggplot(combined_data, aes(x = number_of_fatalities, y = number_of_injuries, size = number_of_tornados, color = tornado_color_factor)) +
  geom_point(alpha = 0.9) +
  scale_x_continuous(expand = c(0,0), limits = c(0,600), breaks = seq(0,600,100)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,9500), breaks = seq(0,9500,2000)) +
  scale_size_continuous(name = "Number of tornados", range = c(3,12)) +
  scale_color_manual(values = colors,
                     labels = c("0-999" = "0-999", "1000-1999" = "1000-1999", "2000-2999" = "2000-2999", "3000-3999" = "3000-3999"),
                     name = "Tornado Range") + 
  geom_label_repel(aes(label = st, color = "black"), size = 3, nudge_x = 1, nudge_y = 1, na.rm = TRUE, show.legend = FALSE) + 
  labs(x = "Number of Fatalities", y = "Number of Injuries", title = "Number of Fatalities vs. Number of Injuries") +
  guides(color = guide_legend(override.aes = list(size = 4))) + 
  theme_minimal() +
  theme_1b() +
  theme (
    axis.text = element_text(color = "black"),
    panel.grid.major = element_line(color = "#E5E5E5"),
    panel.grid.minor = element_line(color = "#E5E5E5")
  ) 

# Display the plot
bubble_chart
```


## Mini Question 2

```{r}
# Create a new variable for decade
new_df <- tornados %>%
  mutate(decade = case_when(
    yr >= 2020 & yr <= 2022 ~ "2020-2022",
    TRUE ~ paste0(substr(yr, 1, 3), "0s")
  )) %>%
  select(decade, loss) %>%
  group_by(decade) %>%
  summarise(
    loss_6 = sum(loss >= 1e6 & loss < 1e7, na.rm = TRUE),
    loss_7 = sum(loss >= 1e7 & loss < 1e8, na.rm = TRUE),
    loss_8 = sum(loss >= 1e8, na.rm = TRUE)
  )

# Display the resulting dataframe
new_df

# Crete long df
long_df <- new_df %>%
  pivot_longer(
    cols = -decade, # Selects all columns except 'decade'
    names_to = "category",
    values_to = "count"
  )

colors <- c(
  "loss_6" = pal[9],
  "loss_7" = pal[7],
  "loss_8" = pal[6]
)

long_df

# Create bar chart
economic_impact <- ggplot(data = long_df, aes(x = decade, y = count, fill = category)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = count), position = position_dodge(width = 0.9), vjust = -0.5, size = 2.5) +
  labs(
    x = "Decade", y = "No. of Tornados",
    title = "Number of US tornados by loss range (in US dollar)"
  ) +
  scale_fill_manual(
    values = colors,
    labels = c(
      "loss_6" = "Loss 1-10 million dollar",
      "loss_7" = "Loss 10-100 million dollar",
      "loss_8" = "Loss over 100 million dollar"
    ),
    name = "Type of tornados"
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0)),
    limits = c(0, 700)
  ) +
  theme_1b() +
  theme(
    axis.title.x = element_text(face = "bold"),
    axis.title.y = element_text(face = "bold"),
    legend.title = element_text(face = "bold"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  ) +
  annotate("rect", xmin = 7.5, xmax = 8.5, ymin = -Inf, ymax = Inf, alpha = 0.1) +
  annotate("text", x = 8, y = 600, label = "Ongoing Decade", size = 4, angle = 90, hjust = 1)
economic_impact
```